name: test_run_on_backside_dev

on: 
  push:
    branches: 
      - backside-dev

jobs:
  phpunit:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - run: ls -a
    - run: cd backside
    - run: composer install
    - run: backside/vendor/bin/phpunit
