name: test_run_on_backside_dev

on: 
  push:
    branches: master

jobs:
  test-php:
      name: Test/Lint PHP
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: 7.4 # Use your PHP version
            extensions: mbstring, bcmath # Setup any required extensions for tests
        - working-directory: backside
        - name: Composer install
          run: composer install
        - name: Run Tests
          run: ./vendor/bin/phpunit
