name: test_run_on_backside_dev

on: 
  push:
    branches: 
      - backside-dev

jobs:
  phpunit:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@backside-dev
    - uses: pxgamer/phpunit-action@master
      with:
        command: backside/tests/

